%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.0 and Fixed-Point Designer 5.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [Theta,dTheta,Bias,P] = IMUKalmanFilter_wrapper_fixpt(Theta,dTheta,Bias,P,Gyro,AccTheta,qw,qb,rw,rt)
    fm = get_fimath();
    Theta_in = fi( Theta, 1, 16, 0, fm );
    dTheta_in = fi( dTheta, 1, 16, 0, fm );
    Bias_in = fi( Bias, 1, 16, 2, fm );
    P_in = fi( P, 1, 32, 4, fm );
    Gyro_in = fi( Gyro, 1, 16, 0, fm );
    AccTheta_in = fi( AccTheta, 1, 16, 0, fm );
    qw_in = fi( qw, 0, 16, 3, fm );
    qb_in = fi( qb, 0, 16, 12, fm );
    rw_in = fi( rw, 0, 16, 12, fm );
    rt_in = fi( rt, 0, 16, 4, fm );
    global T
    [Theta_out,dTheta_out,Bias_out,P_out] = IMUKalmanFilter_fixpt( Theta_in, dTheta_in, Bias_in, P_in, Gyro_in, AccTheta_in, qw_in, qb_in, rw_in, rt_in );
    Theta = double( Theta_out );
    dTheta = double( dTheta_out );
    Bias = double( Bias_out );
    P = double( P_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
